### ISSUE TITLE
wad loading enhancements

### ISSUE THREAD

**Issue by jimmymcson** [pbdot/edge-classic-site-webplayer#1]
replace the choose wad button with something like this:
![image](https://github.com/pbdot/edge-classic-site-webplayer/assets/129529930/7f7d0422-3256-4149-9b3c-3ce518d2e92d)

**Comment by pbdot** [comment]
Hello, thanks for the feature request, I filed it on the edge classic repo and will close down issues on this repo, sorry for the confusion https://github.com/edge-classic/EDGE-classic/issues/566
